In [53]:
import pandas as pd
import numpy as np

In [54]:
from os import listdir
from os.path import isfile, join

# set file path before execution
# filepath should point to the directory where all the csv or data files located

In [55]:
filepath = "."

# list all the valid file names
files = [f for f in listdir(filepath) if isfile(join(filepath, f))]
files = [f for f in files if "csv" in f and f.startswith("201")]
len(files)

90

In [58]:
# determine all the columns that have to be dropped by default
def drop_column_names():
    data = pd.read_csv(filepath +"/2019-01-01.csv")
    drop_columns = []
    for i in data.columns:
        if "normalized" in i:
            drop_columns.append(i)     
    return drop_columns

In [59]:
# columns that have to be dropped
drop_names = drop_column_names()

In [5]:
# put all the dataframes into a list 
master_df_list = []

In [6]:
# iterate over each file and drop the unwanted columns
for file_name in files:
    data = pd.read_csv(file_name)
    data.drop(drop_names, axis = 1, inplace=True)
    master_df_list.append(data.copy())
    print("{} added to master_list".format(file_name))

2019-01-22.csv added to master_list
2019-03-27.csv added to master_list
2019-03-26.csv added to master_list
2019-01-23.csv added to master_list
2019-01-09.csv added to master_list
2019-01-21.csv added to master_list
2019-03-18.csv added to master_list
2019-03-24.csv added to master_list
2019-03-30.csv added to master_list
2019-03-31.csv added to master_list
2019-03-25.csv added to master_list
2019-03-19.csv added to master_list
2019-01-20.csv added to master_list
2019-01-08.csv added to master_list
2019-01-24.csv added to master_list
2019-01-30.csv added to master_list
2019-01-18.csv added to master_list
2019-03-21.csv added to master_list
2019-03-09.csv added to master_list
2019-03-08.csv added to master_list
2019-03-20.csv added to master_list
2019-01-19.csv added to master_list
2019-01-31.csv added to master_list
2019-01-25.csv added to master_list
2019-01-27.csv added to master_list
2019-03-22.csv added to master_list
2019-03-23.csv added to master_list
2019-01-26.csv added to master_list
2019-02-04.csv added to master_list
2019-02-10.csv added to master_list
2019-02-11.csv added to master_list
2019-02-05.csv added to master_list
2019-02-13.csv added to master_list
2019-02-07.csv added to master_list
2019-02-06.csv added to master_list
2019-02-12.csv added to master_list
2019-02-16.csv added to master_list
2019-02-02.csv added to master_list
2019-02-03.csv added to master_list
2019-02-17.csv added to master_list
2019-02-01.csv added to master_list
2019-02-15.csv added to master_list
2019-02-14.csv added to master_list
2019-02-28.csv added to master_list
2019-02-25.csv added to master_list
2019-02-19.csv added to master_list
2019-02-18.csv added to master_list
2019-02-24.csv added to master_list
2019-02-26.csv added to master_list
2019-02-27.csv added to master_list
2019-02-23.csv added to master_list
2019-02-22.csv added to master_list
2019-02-08.csv added to master_list
2019-02-20.csv added to master_list
2019-02-21.csv added to master_list
2019-02-09.csv added to master_list
2019-01-17.csv added to master_list
2019-01-03.csv added to master_list
2019-03-12.csv added to master_list
2019-03-06.csv added to master_list
2019-03-07.csv added to master_list
2019-03-13.csv added to master_list
2019-01-02.csv added to master_list
2019-01-16.csv added to master_list
2019-01-28.csv added to master_list
2019-01-14.csv added to master_list
2019-03-05.csv added to master_list
2019-03-11.csv added to master_list
2019-03-10.csv added to master_list
2019-03-04.csv added to master_list
2019-01-15.csv added to master_list
2019-01-01.csv added to master_list
2019-01-29.csv added to master_list
2019-01-05.csv added to master_list
2019-01-11.csv added to master_list
2019-03-14.csv added to master_list
2019-03-28.csv added to master_list
2019-03-29.csv added to master_list
2019-03-15.csv added to master_list
2019-03-01.csv added to master_list
2019-01-10.csv added to master_list
2019-01-04.csv added to master_list
2019-01-12.csv added to master_list
2019-01-06.csv added to master_list
2019-03-17.csv added to master_list
2019-03-03.csv added to master_list
2019-03-02.csv added to master_list
2019-03-16.csv added to master_list
2019-01-07.csv added to master_list
2019-01-13.csv added to master_list

In [7]:
# generate a master data frame to have all the data
master_df = pd.concat(master_df_list)
master_df.shape

(9577046, 67)

In [8]:
# determine the count of each model in entire dataset
models_count = master_df["model"]
models_count = models_count.value_counts().to_frame()
models_count.columns = ["count"]
models_count['name'] = models_count.index
models_count.reset_index(drop=True)
models_count.shape

(49, 2)

In [9]:
# determine the failure_count of each model in entire dataset
failure_counts = master_df[master_df["failure"]==1].groupby(["model"]).agg({'model':'count'})
failure_counts.columns = ["failed_count"]
failure_counts['name'] = failure_counts.index
failure_counts = failure_counts.reset_index(drop=True)
failure_counts.shape

(20, 2)

In [10]:
# determine the no_failure_count of each model in entire dataset
no_failure_counts = master_df[master_df["failure"]==0].groupby(["model"]).agg({'model':'count'})
no_failure_counts.columns = ["no_failed_count"]
no_failure_counts['name'] = no_failure_counts.index
no_failure_counts = no_failure_counts.reset_index(drop=True)
no_failure_counts.shape

(49, 2)

In [11]:
# combine no_failure_counts and failure_counts into one df
merged_level_1 = pd.merge(no_failure_counts, failure_counts, left_on='name', right_on='name', how="left")
merged_level_1

    no_failed_count                                 name  failed_count
0               540                          DELLBOSS VD           NaN
1              3117                 HGST HDS5C4040ALE630           NaN
2            313381                 HGST HMS5C4040ALE640           2.0
3           1172813                 HGST HMS5C4040BLE640          11.0
4                90                 HGST HMS5C4040BLE641           NaN
5              1245                 HGST HUH721010ALE600           NaN
6             14039                 HGST HUH721212ALE600           1.0
7            259745                 HGST HUH721212ALN604           4.0
8             93595                 HGST HUH728080ALE600           3.0
9              2598                 HGST HUS726040ALE610           NaN
10              626              Hitachi HDS5C4040ALE630           NaN
11               29              Hitachi HDS724040ALE640           NaN
12           108552                        ST10000NM0086           3.0
13               90                       ST1000LM024 HN           NaN
14          2954845                        ST12000NM0007         180.0
15               24                        ST250LM004 HN           NaN
16               42                          ST3160316AS           NaN
17               14                          ST3160318AS           NaN
18               85                           ST320LT007           NaN
19          1989322                          ST4000DM000         107.0
20             4848                          ST4000DM005           NaN
21            50607                        ST500LM012 HN          12.0
22               82                           ST500LM021           NaN
23            14470                           ST500LM030           9.0
24             1113                          ST6000DM001           NaN
25              180                          ST6000DM004           NaN
26           135831                          ST6000DX000           1.0
27           888712                          ST8000DM002          29.0
28              272                          ST8000DM004           1.0
29             2250                          ST8000DM005           NaN
30          1294393                         ST8000NM0055          58.0
31              265  Seagate BarraCuda SSD ZA2000CM10002           NaN
32             1564   Seagate BarraCuda SSD ZA500CM10002           NaN
33              834                      TOSHIBA HDWE160           NaN
34             1798                      TOSHIBA HDWF180           NaN
35            12662                  TOSHIBA MD04ABA400V           NaN
36             4050                  TOSHIBA MD04ABA500V           NaN
37           109403                  TOSHIBA MG07ACA14TA           1.0
38            46955                   TOSHIBA MQ01ABF050          14.0
39            32621                  TOSHIBA MQ01ABF050M           3.0
40              251                       WDC WD1600AAJS           NaN
41               88                       WDC WD2500AAJS           NaN
42                3                       WDC WD3200AAJS           NaN
43               29                       WDC WD3200BEKX           NaN
44               94                         WDC WD40EFRX           NaN
45              982                       WDC WD5000BPKT           NaN
46             4918                       WDC WD5000LPCX           2.0
47            22013                       WDC WD5000LPVX           2.0
48            30522                         WDC WD60EFRX           1.0

In [12]:
# combine models_count and failure_counts into one df
merged_level_2 = pd.merge(models_count, merged_level_1, left_on='name', right_on='name', how="left")
merged_level_2 = merged_level_2.fillna(0)
merged_level_2["failed_count"] = merged_level_2["failed_count"].astype('int32')
merged_level_2 = merged_level_2.sort_values(by='failed_count', ascending=False)
merged_level_2

,count,name,no_failed_count,failed_count
0,2955025,ST12000NM0007,2954845,180
1,1989429,ST4000DM000,1989322,107
2,1294451,ST8000NM0055,1294393,58
4,888741,ST8000DM002,888712,29
12,46969,TOSHIBA MQ01ABF050,46955,14
11,50619,ST500LM012 HN,50607,12
3,1172824,HGST HMS5C4040BLE640,1172813,11
16,14479,ST500LM030,14470,9
6,259749,HGST HUH721212ALN604,259745,4
9,108555,ST10000NM0086,108552,3
10,93598,HGST HUH728080ALE600,93595,3
13,32624,TOSHIBA MQ01ABF050M,32621,3
15,22015,WDC WD5000LPVX,22013,2
5,313383,HGST HMS5C4040ALE640,313381,2
19,4920,WDC WD5000LPCX,4918,2
17,14040,HGST HUH721212ALE600,14039,1
14,30523,WDC WD60EFRX,30522,1
8,109404,TOSHIBA MG07ACA14TA,109403,1
7,135832,ST6000DX000,135831,1
33,273,ST8000DM004,272,1
46,24,ST250LM004 HN,24,0
45,29,WDC WD3200BEKX,29,0
44,29,Hitachi HDS724040ALE640,29,0
43,42,ST3160316AS,42,0
47,14,ST3160318AS,14,0
34,265,Seagate BarraCuda SSD ZA2000CM10002,265,0
41,85,ST320LT007,85,0
40,88,WDC WD2500AAJS,88,0
39,90,ST1000LM024 HN,90,0
38,90,HGST HMS5C4040BLE641,90,0
37,94,WDC WD40EFRX,94,0
36,180,ST6000DM004,180,0
35,251,WDC WD1600AAJS,251,0
42,82,ST500LM021,82,0
24,2250,ST8000DM005,2250,0
32,540,DELLBOSS VD,540,0
31,626,Hitachi HDS5C4040ALE630,626,0
30,834,TOSHIBA HDWE160,834,0
29,982,WDC WD5000BPKT,982,0
28,1113,ST6000DM001,1113,0
27,1245,HGST HUH721010ALE600,1245,0
26,1564,Seagate BarraCuda SSD ZA500CM10002,1564,0
25,1798,TOSHIBA HDWF180,1798,0
23,2598,HGST HUS726040ALE610,2598,0
22,3117,HGST HDS5C4040ALE630,3117,0
21,4050,TOSHIBA MD04ABA500V,4050,0
20,4848,ST4000DM005,4848,0
18,12662,TOSHIBA MD04ABA400V,12662,0
48,3,WDC WD3200AAJS,3,0

In [13]:
merged_level_2.to_csv(r'base_stats.csv', index = False)

# Analysis of Model 1 EXPERIMENTING -

In [17]:
model_1 = master_df[master_df["model"] == "ST12000NM0007"]

In [20]:
# drop all columns that are only NaN
model_1 = model_1.dropna(axis=1, how='all') # 67 to 27 column reduction
model_1

,date,serial_number,model,capacity_bytes,failure,smart_1_raw,smart_3_raw,smart_4_raw,smart_5_raw,smart_7_raw,...,smart_193_raw,smart_194_raw,smart_195_raw,smart_197_raw,smart_198_raw,smart_199_raw,smart_200_raw,smart_240_raw,smart_241_raw,smart_242_raw
1,2019-01-22,ZJV0XJQ4,ST12000NM0007,12000138625024,0,100660576.0,0.0,2.0,0.0,495697950.0,...,2167.0,29.0,100660576.0,0.0,0.0,0.0,0.0,3507.0,3.059038e+10,4.372913e+10
2,2019-01-22,ZJV0XJQ3,ST12000NM0007,12000138625024,0,160729048.0,0.0,1.0,0.0,81624753.0,...,962.0,32.0,160729048.0,0.0,0.0,0.0,0.0,1082.0,9.689933e+09,1.213036e+09
3,2019-01-22,ZJV0XJQ0,ST12000NM0007,12000138625024,0,5880720.0,0.0,6.0,0.0,620826750.0,...,707.0,22.0,5880720.0,0.0,0.0,0.0,0.0,4651.0,3.518872e+10,4.343053e+10
6,2019-01-22,ZJV02XWG,ST12000NM0007,12000138625024,0,132431208.0,0.0,7.0,0.0,679995939.0,...,687.0,23.0,132431208.0,0.0,0.0,0.0,0.0,6016.0,3.550833e+10,4.860857e+10
7,2019-01-22,ZJV1CSVX,ST12000NM0007,12000138625024,0,238709706.0,0.0,2.0,0.0,630213182.0,...,311.0,30.0,238709706.0,0.0,0.0,0.0,0.0,4446.0,3.712289e+10,4.490302e+10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107137,2019-01-13,ZCH07HWT,ST12000NM0007,12000138625024,0,195853592.0,0.0,4.0,0.0,324359126.0,...,1521.0,31.0,195853592.0,0.0,0.0,0.0,0.0,10295.0,5.232617e+10,8.654168e+10
107138,2019-01-13,ZCH068KT,ST12000NM0007,12000138625024,0,131688600.0,0.0,2.0,0.0,90142737.0,...,706.0,33.0,131688600.0,0.0,0.0,0.0,0.0,10173.0,5.183079e+10,8.257836e+10
107143,2019-01-13,ZCH068KY,ST12000NM0007,12000138625024,0,181497936.0,0.0,7.0,0.0,51217025.0,...,724.0,27.0,181497936.0,0.0,0.0,0.0,0.0,10179.0,5.060611e+10,8.214391e+10
107148,2019-01-13,ZCH0CJ40,ST12000NM0007,12000138625024,0,227430824.0,0.0,5.0,0.0,839533797.0,...,459.0,29.0,227430824.0,0.0,0.0,0.0,0.0,8740.0,4.092018e+10,6.868238e+10
107165,2019-01-13,ZJV1CSVC,ST12000NM0007,12000138625024,0,115554800.0,0.0,2.0,0.0,621014610.0,...,324.0,30.0,115554800.0,0.0,0.0,0.0,0.0,4234.0,3.637612e+10,4.601492e+10

In [24]:
cols = model_1.select_dtypes([np.number]).columns
std = model_1[cols].std()
cols_to_drop = std[std==0].index
cols_to_drop
# df.drop(cols_to_drop, axis=1)

Index(['smart_3_raw', 'smart_10_raw', 'smart_200_raw'], dtype='object')

In [28]:
# returns the total number of null values in each column
# model_1.isnull().sum(axis = 0)

date                0
serial_number       0
model               0
capacity_bytes      0
failure             0
smart_1_raw       231
smart_3_raw       231
smart_4_raw       231
smart_5_raw       231
smart_7_raw       231
smart_9_raw       231
smart_10_raw      231
smart_12_raw      231
smart_187_raw     231
smart_188_raw     231
smart_190_raw     231
smart_192_raw     231
smart_193_raw     231
smart_194_raw     231
smart_195_raw     231
smart_197_raw     231
smart_198_raw     231
smart_199_raw     231
smart_200_raw     231
smart_240_raw     231
smart_241_raw     231
smart_242_raw     231
dtype: int64

In [30]:
# returns the column names with atleast one empty NaN value
# model_1.columns[model_1.isna().any()].tolist()

['smart_1_raw',
 'smart_3_raw',
 'smart_4_raw',
 'smart_5_raw',
 'smart_7_raw',
 'smart_9_raw',
 'smart_10_raw',
 'smart_12_raw',
 'smart_187_raw',
 'smart_188_raw',
 'smart_190_raw',
 'smart_192_raw',
 'smart_193_raw',
 'smart_194_raw',
 'smart_195_raw',
 'smart_197_raw',
 'smart_198_raw',
 'smart_199_raw',
 'smart_200_raw',
 'smart_240_raw',
 'smart_241_raw',
 'smart_242_raw']

In [32]:
# model_1[model_1.isnull().any(axis=1)]

array([0])

In [33]:
# drops all rows with even one NaN value
print(model_1.shape)
model_1 = model_1.dropna()
print(model_1.shape)

(2955025, 27)
(2954794, 27)

In [40]:
# find all columns that are filled with the same value
columns_with_same_values = model_1.columns[model_1.nunique() <= 1].tolist()
# do not remove the columns 'model' and 'capacity_bytes'
columns_with_same_values.remove('model')
columns_with_same_values.remove('capacity_bytes')
columns_with_same_values

['smart_3_raw', 'smart_10_raw', 'smart_200_raw']

In [41]:
print(model_1.shape)
model_1 = model_1.drop(columns_with_same_values, axis=1)
print(model_1.shape)

(2954794, 27)
(2954794, 24)

In [44]:
model_1 = model_1.sort_values(['serial_number', 'date'], ascending=[True, True])

,date,serial_number,model,capacity_bytes,failure,smart_1_raw,smart_4_raw,smart_5_raw,smart_7_raw,smart_9_raw,...,smart_192_raw,smart_193_raw,smart_194_raw,smart_195_raw,smart_197_raw,smart_198_raw,smart_199_raw,smart_240_raw,smart_241_raw,smart_242_raw
61375,2019-01-01,ZCH00XGL,ST12000NM0007,12000138625024,0,110122224.0,2.0,0.0,964512361.0,7828.0,...,148.0,510.0,23.0,110122224.0,0.0,0.0,0.0,7710.0,4.540083e+10,3.844960e+10
61311,2019-01-02,ZCH00XGL,ST12000NM0007,12000138625024,0,80289632.0,2.0,0.0,966845678.0,7853.0,...,148.0,511.0,23.0,80289632.0,0.0,0.0,0.0,7735.0,4.545387e+10,3.861087e+10
61343,2019-01-03,ZCH00XGL,ST12000NM0007,12000138625024,0,42176904.0,2.0,0.0,969120783.0,7877.0,...,149.0,512.0,23.0,42176904.0,0.0,0.0,0.0,7758.0,4.551260e+10,3.875816e+10
61261,2019-01-04,ZCH00XGL,ST12000NM0007,12000138625024,0,67951032.0,2.0,0.0,972358892.0,7899.0,...,149.0,513.0,25.0,67951032.0,0.0,0.0,0.0,7781.0,4.558486e+10,3.895582e+10
61996,2019-01-05,ZCH00XGL,ST12000NM0007,12000138625024,0,156529824.0,2.0,0.0,977487475.0,7925.0,...,150.0,514.0,24.0,156529824.0,0.0,0.0,0.0,7807.0,4.567620e+10,3.919719e+10
61995,2019-01-06,ZCH00XGL,ST12000NM0007,12000138625024,0,102865000.0,2.0,0.0,979544089.0,7948.0,...,151.0,515.0,25.0,102865000.0,0.0,0.0,0.0,7830.0,4.572466e+10,3.933922e+10
61967,2019-01-07,ZCH00XGL,ST12000NM0007,12000138625024,0,162850936.0,2.0,0.0,985532416.0,7972.0,...,152.0,516.0,25.0,162850936.0,0.0,0.0,0.0,7853.0,4.585590e+10,3.951210e+10
61910,2019-01-08,ZCH00XGL,ST12000NM0007,12000138625024,0,159113176.0,2.0,0.0,987909834.0,7998.0,...,153.0,517.0,24.0,159113176.0,0.0,0.0,0.0,7878.0,4.592304e+10,3.968536e+10
61884,2019-01-09,ZCH00XGL,ST12000NM0007,12000138625024,0,129966176.0,2.0,0.0,990044730.0,8021.0,...,154.0,518.0,23.0,129966176.0,0.0,0.0,0.0,7902.0,4.598717e+10,3.983622e+10
61670,2019-01-10,ZCH00XGL,ST12000NM0007,12000138625024,0,101723008.0,2.0,0.0,992359347.0,8045.0,...,154.0,519.0,24.0,101723008.0,0.0,0.0,0.0,7926.0,4.603838e+10,4.000091e+10
61669,2019-01-11,ZCH00XGL,ST12000NM0007,12000138625024,0,191247936.0,2.0,0.0,997047405.0,8070.0,...,155.0,520.0,24.0,191247936.0,0.0,0.0,0.0,7950.0,4.614540e+10,4.022756e+10
61609,2019-01-12,ZCH00XGL,ST12000NM0007,12000138625024,0,239340488.0,2.0,0.0,1412575.0,8093.0,...,156.0,521.0,23.0,239340488.0,0.0,0.0,0.0,7974.0,4.623761e+10,4.042758e+10
61494,2019-01-13,ZCH00XGL,ST12000NM0007,12000138625024,0,189632880.0,2.0,0.0,3283368.0,8116.0,...,157.0,522.0,24.0,189632880.0,0.0,0.0,0.0,7996.0,4.629164e+10,4.056799e+10
61295,2019-01-14,ZCH00XGL,ST12000NM0007,12000138625024,0,42352936.0,2.0,0.0,9284925.0,8141.0,...,157.0,523.0,24.0,42352936.0,0.0,0.0,0.0,8021.0,4.644755e+10,4.075308e+10
60948,2019-01-15,ZCH00XGL,ST12000NM0007,12000138625024,0,7841808.0,2.0,0.0,11477808.0,8165.0,...,158.0,524.0,24.0,7841808.0,0.0,0.0,0.0,8045.0,4.650337e+10,4.090689e+10
60945,2019-01-16,ZCH00XGL,ST12000NM0007,12000138625024,0,214354712.0,2.0,0.0,13737735.0,8189.0,...,159.0,525.0,25.0,214354712.0,0.0,0.0,0.0,8069.0,4.656921e+10,4.104756e+10
60944,2019-01-17,ZCH00XGL,ST12000NM0007,12000138625024,0,171378584.0,2.0,0.0,15627908.0,8213.0,...,160.0,526.0,24.0,171378584.0,0.0,0.0,0.0,8093.0,4.661315e+10,4.120479e+10
60923,2019-01-18,ZCH00XGL,ST12000NM0007,12000138625024,0,16727944.0,2.0,0.0,19995340.0,8237.0,...,160.0,527.0,25.0,16727944.0,0.0,0.0,0.0,8116.0,4.669673e+10,4.145483e+10
60922,2019-01-19,ZCH00XGL,ST12000NM0007,12000138625024,0,95947240.0,2.0,0.0,24260522.0,8261.0,...,161.0,528.0,23.0,95947240.0,0.0,0.0,0.0,8141.0,4.675647e+10,4.171846e+10
60922,2019-01-20,ZCH00XGL,ST12000NM0007,12000138625024,0,73986912.0,2.0,0.0,26006497.0,8285.0,...,161.0,529.0,24.0,73986912.0,0.0,0.0,0.0,8164.0,4.678966e+10,4.190745e+10

# FINAL CLEANING CODE

In [45]:
# set the model name here 
model_name = "ST12000NM0007"

In [46]:
# data cleaning operations
def data_cleaning(model_name):
    model_1 = master_df[master_df["model"] == model_name]
    
    # drop all columns that are only NaN
    model_1 = model_1.dropna(axis=1, how='all')
    print("initial column drop done")
    
    # drops all rows with even one NaN value
    model_1 = model_1.dropna()
    print("initial row drop done")
    
    # find all columns that are filled with the same value and drop them
    columns_with_same_values = model_1.columns[model_1.nunique() <= 1].tolist()
    
    # do not remove the columns 'model' and 'capacity_bytes'
    columns_with_same_values.remove('model')
    columns_with_same_values.remove('capacity_bytes')
    model_1 = model_1.drop(columns_with_same_values, axis=1)
    print("repeating cloumn value drop done")
    
    # sort the dataframe based on serial_number and date
    model_1 = model_1.sort_values(['serial_number', 'date'], ascending=[True, True])
    print("sort done")
    return model_1

In [47]:
# cleaned data
cleaned_data = data_cleaning(model_name)
export_filename = model_name+".csv"
cleaned_data.to_csv(export_filename, index = False)